### ISSUE TITLE
Support for 0903.4 and 0903.5 VMTI

### ISSUE THREAD

**Issue by cnithianandam** [impleotv/stanag-player-sdk-release#1]
In your documentation it says you support 0903.3 VMTI metadata. Is is possible to support 0903.4 and possibly 0903.5? In an ideal case we would like to use this tool to input a UDP stream with 0903.4 detections and have them show in the video.

**Comment by impleotv** [comment]
Well, actually we do support 0903.4 (I believe we removed 0903.3 as that revision was too buggy - they messed up some tags, making everything incompatible). 0903.5 should also work, though not 100% of the tags are implemented.
